version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@react-native-async-storage/async-storage"
    versions:
    - 1.14.1
    - 1.15.1
    - 1.15.2
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: react-native-screens
    versions:
    - 2.18.0
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.3
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.3
  - dependency-name: babel-jest
    versions:
    - 26.6.3
  - dependency-name: "@types/react-test-renderer"
    versions:
    - 17.0.1
